// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LanguageSwitcher": {
    "en": "EN",
    "es": "ES"
  },
"Navigation": {
  "work": "Work",
  "services": "Services",
  "stack": "Stack",
  "about": "About",
  "contact": "Contact",
  "cta": "Contact"
},
  "Hero": {
    "badge": "Available for freelance and premium product builds.",
    "role": "Full Stack Developer",
    "title": "I build premium web products that combine elegant UX, robust architecture, and real business value.",
    "description": "From polished interfaces to scalable backend systems, I create modern digital experiences designed to perform, convert, and grow.",
    "primaryCta": "View Projects",
    "secondaryCta": "Let's Work Together",
    "focusLabel": "Selected Focus",
    "focusTitle": "Premium UI + robust backend + product thinking",
    "bullet1": "High-end frontend execution",
    "bullet2": "Scalable backend architecture",
    "bullet3": "Real-time systems and integrations",
    "bullet4": "Business-focused product builds"
  },
  "Projects": {
    "eyebrow": "Featured Work",
    "title": "Selected projects that show both craft and technical depth.",
    "description": "I focus on work that demonstrates design sensitivity, strong engineering, and business-oriented execution.",
    "cta": "View Case Study",
    "items": {
      "iotPlatform": {
        "title": "Enterprise IoT Platform",
        "category": "Full Stack · Real-Time",
        "description": "A real-time IoT platform with live telemetry, MQTT integration, device state handling, and premium admin dashboards."
      },
      "ecommerce": {
        "title": "Modern E-Commerce Experience",
        "category": "E-Commerce · UX",
        "description": "A refined online store with premium shopping flows, address management, wishlist, and scalable architecture."
      },
      "creativePlatform": {
        "title": "Creative Collaboration Platform",
        "category": "Community · Product Design",
        "description": "A visually rich platform for creators with media workflows, interaction systems, and strong UI direction."
      }
    }
  },
  "Services": {
    "eyebrow": "Services",
    "title": "What I can build and improve.",
    "description": "I work across interface, backend, product and systems integration to deliver experiences that feel polished and dependable.",
    "items": {
      "frontend": {
        "title": "Frontend Engineering",
        "description": "Responsive, polished interfaces with strong hierarchy, premium styling, motion and performance."
      },
      "backend": {
        "title": "Backend & APIs",
        "description": "Scalable servers, authentication, roles, maintainable APIs and solid data modeling."
      },
      "fullstack": {
        "title": "Full Stack Product Development",
        "description": "From concept to launch, I build digital products that feel cohesive, robust and production-ready."
      },
      "realtime": {
        "title": "Real-Time Systems",
        "description": "Dashboards, sockets, MQTT workflows and live connected product experiences."
      }
    }
  },
  "Stack": {
    "eyebrow": "Stack",
    "title": "The tools behind the work.",
    "description": "I choose technologies based on product goals, maintainability and performance, not hype alone."
  },
  "About": {
    "eyebrow": "About Me",
    "title": "I build products with taste, structure and intent.",
    "description": "I’m a Full Stack Developer focused on creating premium digital experiences — the kind that feel visually refined, technically solid and genuinely useful.",
    "sideEyebrow": "What sets me apart",
    "sideTitle": "A product mindset with engineering depth.",
    "sideDescription": "I care about the details users notice and the architecture teams depend on.",
    "point1": "I combine polished frontend execution with backend depth.",
    "point2": "I think in terms of product quality, not only code completion.",
    "point3": "I build systems that look premium and feel reliable.",
    "point4": "I care about maintainability, user trust and real delivery."
  },
  "Contact": {
    "eyebrow": "Let's build something great",
    "title": "Need a developer who can make the product look premium and hold up technically?",
    "description": "I’m open to freelance work, collaborations, and high-quality product builds. Let’s turn your idea into something sharp, credible, and launch-ready.",
    "email": "Email Me",
    "github": "GitHub",
    "linkedin": "LinkedIn"
  },
  "Footer": {
    "rights": "All rights reserved.",
    "builtWith": "Built with Next.js, Tailwind CSS, and a premium obsession."
  }
  ,
  "Metadata": {
    "title": "Luis Manuel Santos | Full Stack Developer",
    "description": "Premium full stack developer portfolio focused on elegant UX, scalable architecture and modern digital products."
  }
};
export default messages;